---
- name: IndySCC hosts configured
  hosts: all

  tasks:
  - name: Mount directory /scratch created
    ansible.builtin.file:
      path: /scratch
      state: directory
      mode: '0777'

  - name: Ceph keyring file templated
    ansible.builtin.template:
      src: ceph.client.indyscc-scratch.j2
      dest: "/etc/ceph/ceph.client.indyscc-{{ team_name }}-rw.keyring"
      mode: '0644'

  - name: Manila share /scratch mount added to fstab
    ansible.posix.mount:
      src: '{{ share_export_location }}'
      path: '/scratch'
      opts: 'name=indyscc-{{ team_name }}-rw,nofail,noatime,_netdev,x-systemd.automount,x-systemd.device-timeout=1s,x-systemd.idle-timeout=600s,rw'
      state: mounted
      fstype: ceph

  - name: 'Force a systemd configs reload just to be sure the automount works correctly'
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: GPU presence detected
    ansible.builtin.shell: set -o pipefail && lspci | grep -i nvidia
    register: gpu_return
    failed_when: gpu_return.rc == 2

  - name: GPU driver repo installed if GPU is present
    ansible.builtin.command: "dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/cuda-rhel9.repo"
    when: gpu_return.rc == 0

  - name: GPU driver module enabled if GPU is present
    ansible.builtin.command: "dnf module enable -y nvidia-driver:560-dkms"
    when: gpu_return.rc == 0

  - name: GPU driver installed if GPU is present
    ansible.builtin.command: "dnf module install -y nvidia-driver:560-dkms"
    when: gpu_return.rc == 0

  - name: Submissions server credential file templated
    ansible.builtin.template:
      src: submission-server-creds.txt.j2
      dest: "/home/rocky/submission-server-creds.txt"
      mode: '0660'
      owner: rocky
      group: rocky

  - name: Timezone set 
    ansible.builtin.command: "timedatectl set-timezone America/Indianapolis"

  - name: System reboot if GPU drivers were installed
    ansible.builtin.reboot:
    when: gpu_return.rc == 0
